# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('spotify', models.CharField(blank=True, max_length=200, null=True)),
                ('soundcloud', models.URLField(blank=True, null=True)),
                ('snapchat', models.CharField(blank=True, max_length=200, null=True)),
                ('snapcode', models.ImageField(null=True, upload_to=b'')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
